[ DRAFT ] [ layer ] Mixed precision forwarding / backwarding for bn layer
nnstreamer/nntrainer pull request #2462
Opened 2024-02-06 01:46 UTC by skykongkong8

- According to recent papers in mixed precision, when it comes to computation of statistics in bn layer, we should use fp32 values
- input(fp16) <-> BN_layer(fp16 weight, but compute with fp32 and re-cast to fp16) <-> output(fp16)
- Although we need a bulky code block for this, I believe we can revisit here for cleaner code when TensorV2 becomes official

**Self evaluation:**
1. Build test:     [X]Passed [ ]Failed [ ]Skipped
2. Run test:     [X]Passed [ ]Failed [ ]Skipped

2024-02-06 03:45 UTC, djeong20 commented on nntrainer/layers/bn_layer.cpp
> +    TensorDim gamma_dim = gamma.getDim();
same here

2024-02-26 06:49 UTC, skykongkong8 commented on nntrainer/layers/bn_layer.cpp
> +    TensorDim gamma_dim = gamma.getDim();
Applied!

2024-02-29 09:11 UTC, baek2sm approved these changes
LGTM

2024-03-07 01:47 UTC, EunjuYang commented on nntrainer/layers/bn_layer.cpp
> +      Tensor dgamma = context.getWeightGrad(wt_idx[BNParams::gamma]);
is it `Tensor &dgamma = context.getWeightGrad(wt_idx[BNParams::gamma]);` ?

2024-04-16 00:02 UTC, SeoHyungjun approved these changes
LGTM

2024-04-18 07:54 UTC, jijoongmoon requested changes
I dont think this is the right way to enable the mixed precision. please consider #2455

2024-04-22 23:53 UTC, skykongkong8 commented
This PR is no longer needed. Close.

2024-04-22 23:53 UTC, closed without merging