[ BUILD ] Add 16K shared lib package option for Android
nnstreamer/nntrainer pull request #2699
Opened 2024-08-07 02:10 UTC by jijoongmoon

Android encourage to use 16KB package for the shared library. This PR add the 16KB package option and also recommand to use ndk which is higher or equal version of r27.

Resolves:

**Self evaluation:**
1. Build test:	 [X]Passed [ ]Failed [ ]Skipped
2. Run test:	 [X]Passed [ ]Failed [ ]Skipped

2024-08-12 06:06 UTC, DonghakPark approved these changes
LGTM

2024-08-12 23:57 UTC, djeong20 requested changes
we should also update `Application.mk` to support 16 KB alignment with Android NDK version r27 and higher. [(link)](https://developer.android.com/guide/practices/page-sizes#compile-r26-lower)

2024-08-13 01:36 UTC, DonghakPark commented
> we should also update `Application.mk` to support 16 KB alignment with Android NDK version r27 and higher. [(link)](https://developer.android.com/guide/practices/page-sizes#compile-r26-lower)

added Flags for all Android.mk file. Please Take a look #2705

2024-08-13 02:18 UTC, djeong20 commented
> added Flags for all Android.mk file. Please Take a look #2705

updating `Android.mk` is to compile with NDK version r26 or lower. The problem is whether we support NDK version r26 or lower or restrict to use of version r27 or higher.

> Regardless, it is recommended to move to Android NDK r27 or higher to update to the 16 KB ELF-aligned version of the C++ standard library. Otherwise, your app will fail to install on 16 KB devices today.

if we restrict it to use Android NDK version r27 or higher, we do not need to change `Android.mk` and only update `Application.mk`.

2024-08-13 02:30 UTC, DonghakPark commented
> > added Flags for all Android.mk file. Please Take a look #2705
> 
> updating `Android.mk` is to compile with NDK version r26 or lower. The problem is whether we support NDK version r26 or lower or restrict to use of version r27 or higher.
> 
> > Regardless, it is recommended to move to Android NDK r27 or higher to update to the 16 KB ELF-aligned version of the C++ standard library. Otherwise, your app will fail to install on 16 KB devices today.
> 
> if we restrict it to use Android NDK version r27 or higher, we do not need to change `Android.mk` and only update `Application.mk`.

Oh. i see !!
Would it not be necessary to set up in Android.mk as well for when the ndk version is below 27?

2024-08-13 23:42 UTC, djeong20 commented
> Would it not be necessary to set up in Android.mk as well for when the ndk version is below 27?

you're right! If we plan to support the ndk version below 27, we should specify these flags. though, I'm not sure what would be the right choice. maybe we can allow ndk version 26 <= for now, then check the ndk version and print a proper message to upgrade to r27.

2024-08-29 04:08 UTC, merged