[lr] Add CosineAnnealing Learning Rate Scheduler
nnstreamer/nntrainer pull request #2754
Opened 2024-10-10 12:24 UTC by lhw414

This PR adds the [CosineAnnealingLearningRateScheduler](https://pytorch.org/docs/stable/generated/torch.optim.lr_scheduler.CosineAnnealingLR.html) class, which adjusts the learning rate using a cosine annealing schedule. 

The implementation includes setting the max/min learning rates, decay steps, and proper error handling for missing properties.

2024-10-11 00:35 UTC, EunjuYang commented
First of all, thank you for your contribution and PR.
We're going to review your PR. Before that, however, could you please check the CI issue? The NNTrainer's CI checks C++ formatting. 
For more information, please refer to this [page](https://github.com/nnstreamer/nntrainer/blob/main/docs/coding-convention.md).

2024-10-11 02:03 UTC, lhs8928 requested changes

2024-10-11 08:18 UTC, baek2sm commented on nntrainer/optimizers/lr_scheduler_cosine.cpp
> +  CosineAnnealingLearningRateScheduler::setProperty(left);
To add a little more explanation, property setting is completed while calling the loadProperties function, and the return value(left) contains values without matching property keys. So if there is a left value, you can make an exception.

You may modify it according to the following codes.
`void CosineAnnealingLearningRateScheduler::setProperty(
  const std::vector<std::string> &values) {
  auto left = loadProperties(values, lr_props);
  NNTR_THROW_IF(left.size(), std::invalid_argument)
    << "[CosineAnnealingLearningRateScheduler] There are unparsed properties";
}`

2024-10-11 08:26 UTC, baek2sm requested changes

2024-10-11 08:26 UTC, baek2sm commented on nntrainer/optimizers/lr_scheduler_cosine.cpp
> +  CosineAnnealingLearningRateScheduler::setProperty(left);
To add a little more explanation, property setting is completed while calling the loadProperties function, and the return value(left) contains values without matching property keys. So if there is a left value, you can make an exception.

You may modify it according to the following codes.
`void CosineAnnealingLearningRateScheduler::setProperty(
  const std::vector<std::string> &values) {
  auto left = loadProperties(values, lr_props);
  NNTR_THROW_IF(left.size(), std::invalid_argument)
    << "[CosineAnnealingLearningRateScheduler] There are unparsed properties";
}`

2024-10-11 08:29 UTC, baek2sm commented
@DonghakPark For smooth code review process regarding this task, I have asked them to split the codes into smaller parts. Test codes will be uploaded later :)

2024-10-12 15:02 UTC, lhw414 commented on nntrainer/optimizers/lr_scheduler_cosine.cpp
> +  CosineAnnealingLearningRateScheduler::setProperty(left);
There was a mistake during the implementation process while referencing multiple codes. It has been corrected to implement the functionality without calling methods from other classes.

2024-10-12 15:03 UTC, lhw414 commented on nntrainer/optimizers/lr_scheduler_cosine.cpp
> +  CosineAnnealingLearningRateScheduler::exportTo(exporter, method);
Same with setProperty().
I fixed it.

2024-10-12 15:03 UTC, lhw414 commented on nntrainer/optimizers/lr_scheduler_cosine.cpp
> +  auto lr = CosineAnnealingLearningRateScheduler::getLearningRate(iteration);
Same with setProperty().
I fixed it.

2024-10-12 15:03 UTC, lhw414 commented on nntrainer/optimizers/lr_scheduler_cosine.cpp
> +  CosineAnnealingLearningRateScheduler::finalize();
Same with setProperty().
I fixed it.

2024-10-12 15:10 UTC, lhw414 commented
I have a quick question. The [.clang-format file](https://github.com/nnstreamer/nntrainer/blob/main/.clang-format) does not have an option like InsertNewlineAtEOF: true, but TAOS's pre-build check verifies if there is a newline at the end of the file. I'm curious if this is because contributors generally use the "insert newline at EOF" option in their IDEs by default, or if there is another reason for the absence of such an option in clang-format.

2024-10-14 04:40 UTC, DonghakPark commented
> @DonghakPark For smooth code review process regarding this task, I have asked them to split the codes into smaller parts. Test codes will be uploaded later :)

Thank you. By splitting commits, it will become much clearer to review them, and when looking at the history later on, we can clearly see the points where changes were made per feature.

2024-10-14 07:49 UTC, baek2sm approved these changes

2024-10-14 08:58 UTC, EunjuYang approved these changes
LGTM

2024-10-15 09:22 UTC, DonghakPark approved these changes
LGTM!

2024-10-18 01:23 UTC, lhs8928 approved these changes
LGTM

2024-10-18 01:28 UTC, lhs8928 commented
How about we use full name "cosine annealing" for this learning rate instead of just "cosine"?

2024-10-20 23:08 UTC, merged