New add conv transpose
nnstreamer/nntrainer pull request #2781
Opened 2024-11-01 11:07 UTC by sugsugsug

2024-11-04 00:03 UTC, jijoongmoon commented
Please check the CI reviews (pre & post) and then we can review the code.

2024-11-04 05:36 UTC, EunjuYang commented
Thank you for your contribution 😀 
NNTrainer requires a contributor to follow a specific coding convention with signing off. Please refer to this contribution guide [[link](https://github.com/nnstreamer/nntrainer/blob/main/docs/contributing.md)]. For the details, please check the CI review.

2024-11-05 02:34 UTC, DonghakPark reviewed
As @jijoongmoon @EunjuYang mentioned
Please review the following checklist items for compliance.
1. Check Clang-format 
2. Fill commit body (more detail explain)
3. check signed-off 
4. doxygen tag

2024-11-13 07:01 UTC, baek2sm requested changes
Currently, there is an unittest-error in the compiler part. Specifically, the `tf_schema.fbs` script is causing problem. I don't think you need to work on the tf_schema part now, so it seems okay to exclude the `tf_schema.fbs` script from the commit.

If you exclude that script from the commit and perform a rebase (`nntrainer-api-common.h` file), then i think, you can pass the CI.

2024-11-29 00:28 UTC, DonghakPark commented
Please rebase upstream-main then it will pass all ci 
```
git rebase upstream/main
```

2024-11-29 00:29 UTC, DonghakPark approved these changes

2024-12-04 07:28 UTC, baek2sm approved these changes

2024-12-04 10:09 UTC, merged