[ minor ] bugfix in printing error log (model_commo_properties / LossScale)
nnstreamer/nntrainer pull request #2825
Opened 2024-12-11 05:28 UTC by EunjuYang

- This commit fixes a minor error to print error log.
- This commit adds a condition to print the error log.

**Self evaluation:**
1. Build test: [x]Passed [ ]Failed [ ]Skipped
2. Run test: [x]Passed [ ]Failed [ ]Skipped

2024-12-11 05:29 UTC, skykongkong8 approved these changes
LGTM, but in this case, how about comparing float with stricter standard? 

something like:
```C++
if (std::fpclassify(value) == FP_ZERO)
...
```

2024-12-12 03:13 UTC, djeong20 approved these changes
LGTM

2024-12-12 10:12 UTC, myungjoo approved these changes

2024-12-12 10:13 UTC, myungjoo requested changes
Check the return.

2024-12-17 06:48 UTC, EunjuYang commented on nntrainer/models/model_common_properties.cpp
> +    ml_loge("Loss scale cannot be 0");
I missed it! Thank you for pointing it out. I updated the part. Thank you.

2024-12-17 23:20 UTC, baek2sm approved these changes
LGTM

2024-12-19 02:36 UTC, jijoongmoon approved these changes
LGTM

2024-12-20 06:31 UTC, merged