Add ComputeEngine Property for choosing Engine
nnstreamer/nntrainer pull request #2827
Opened 2024-12-16 02:19 UTC by jijoongmoon

This PR add ComputeEngine Enum Property.
Enum elements are "cpu", "gpu", "qnn" for now.
The property format is "engine=qnn".

**Self evaluation:**
1. Build test:	 [X]Passed [ ]Failed [ ]Skipped
2. Run test:	 [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: jijoong.moon <jijoong.moon@samsung.com>

2024-12-16 06:06 UTC, djeong20 approved these changes
LGTM!

2024-12-16 06:08 UTC, skykongkong8 approved these changes
Almost first official stepping stone for supporting QNN as compute engine on the nntrainer! Great!

2024-12-16 10:57 UTC, myungjoo commented on nntrainer/layers/layer_node.cpp
> +  return ml::train::LayerComputeEngine::CPU;
If this function is called frequently and may affect the latency, you may use:
```
if (key[0] == 'q')
  return  QNN;
if (key[0] == 'g')
  return GPU;
return CPU;
```

If you want a generalized code (wtih a bit of inefficiency), use EnumStr
```
for (i = 0; i < arraysize(EnumStr); i++) {
  if (istrequal(key, EnumStr[i])
    return EnumList[i];
}
```

2024-12-17 07:17 UTC, EunjuYang approved these changes
LGTM ! 🚀

2024-12-17 07:30 UTC, EunjuYang requested changes
It seems tflite unittests face some failures. I guess you need to update `node_exporter.h` as well.

https://github.com/nnstreamer/nntrainer/blob/712f6c313c953eb8491ffc6c3f73c0bd7165f6f3/nntrainer/utils/node_exporter.h#L246-L253

2024-12-24 00:13 UTC, EunjuYang approved these changes

2024-12-24 11:12 UTC, closed without merging