[databuffer] Cleanup databuffers for ccapi
nnstreamer/nntrainer pull request #638
Opened 2020-10-12 01:25 UTC by kparichay

Cleanup databuffer headers for ccapi

See also #199

**Self evaluation:**
1. Build test: [x]Passed [ ]Failed [ ]Skipped
2. Run test: [x]Passed [ ]Failed [ ]Skipped

Signed-off-by: Parichay Kapoor <pk.kapoor@samsung.com>

2020-10-12 06:03 UTC, zhoonit approved these changes
LGTM

2020-10-16 01:40 UTC, jijoongmoon commented on nntrainer/include/databuffer_util.h
> + * @file	addition_layer.h
check filename?

2020-10-16 01:42 UTC, jijoongmoon commented on nntrainer/src/databuffer_file.cpp
> +  do {                                                                   \
This already set in databuffer_util.h.

2020-10-16 01:42 UTC, jijoongmoon commented on nntrainer/src/databuffer_func.cpp
> +  do {                                                                   \
ditto

2020-10-16 01:43 UTC, jijoongmoon requested changes
need to check.

2020-10-16 11:39 UTC, kparichay commented on nntrainer/include/databuffer_util.h
> + * @file	addition_layer.h
updated.

2020-10-16 11:39 UTC, kparichay commented on nntrainer/src/databuffer_file.cpp
> +  do {                                                                   \
yes, removed.

2020-10-16 11:39 UTC, kparichay commented on nntrainer/src/databuffer_func.cpp
> +  do {                                                                   \
removed.

2020-10-19 01:18 UTC, jijoongmoon approved these changes
LGTM

2020-10-19 01:18 UTC, merged