[Fix/Optimizer] Fix decay_rate application
nnstreamer/nntrainer pull request #674
Opened 2020-10-28 04:57 UTC by zhoonit

There was a bug that decay_rate were always applied when it is set to
default value. Becuase `decay_steps != -1` was evaluated to true.

This patch fixes the issue.

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: Jihoon Lee <jhoon.it.lee@samsung.com>

2020-10-28 05:17 UTC, jijoongmoon approved these changes
LGTM

2020-10-29 07:25 UTC, kparichay requested changes
decay_steps should be made integer as it counts the number of steps which can't be float.
Please update `decay_steps` to unsigned int type to resolve this issue than this hot fix.
Also, add a check that decay_step must be positive, (decay_step of 0 is also an error)

2020-11-02 02:34 UTC, zhoonit commented
> decay_steps should be made integer as it counts the number of steps which can't be float.
> Please update `decay_steps` to unsigned int type to resolve this issue than this hot fix.
> Also, add a check that decay_step must be positive, (decay_step of 0 is also an error)

Fixed. Thank you for the suggestion :)

2020-11-02 06:33 UTC, kparichay approved these changes
LGTM

2020-11-02 06:39 UTC, merged