[meson] Set meson buildtype to release
nnstreamer/nntrainer pull request #942
Opened 2021-02-05 07:52 UTC by kparichay

Setting -O optimization manually gives meson warnings.
Instead update meson buildtype to release
This sets debug to 0 and optimization to level 3.

Signed-off-by: Parichay Kapoor <pk.kapoor@samsung.com>

2021-02-15 07:59 UTC, jijoongmoon commented on meson.build
>    ]
any reason to change?? much faster??

2021-02-15 08:00 UTC, jijoongmoon approved these changes
LGTM

2021-02-15 08:14 UTC, zhoonit commented
Meson has buildtypes as a [builtin options](https://mesonbuild.com/Builtin-options.html) which is defaulted to be debug.
Deleting -O2 seems good, how about we relying on the meson option?

2021-02-17 01:15 UTC, lhs8928 approved these changes
LGTM

2021-02-17 03:18 UTC, zhoonit requested changes
Meson has buildtype as a builtin options which is defaulted to be debug.
Deleting -O2 seems good, and for the flag, how about we relying on the meson option?

2021-02-22 04:45 UTC, kparichay commented
> Meson has buildtype as a builtin options which is defaulted to be debug.
> Deleting -O2 seems good, and for the flag, how about we relying on the meson option?

Default option of `debug` for `buildtype` keeps optimization level to be 0 and `debug` mode enabled - https://mesonbuild.com/Builtin-options.html, which IMO isn't desirable for release.
If you want more fine-grained control, `buildtype` can be `plain` and specify optimization `-o2` with meson variables.

2021-02-22 05:24 UTC, zhoonit commented
Aside from it, could you check `nntrainer.spec:279` which is building `plain`. I think it would override `buildtype=release` ?

2021-02-22 05:24 UTC, zhoonit approved these changes
>  Default option of debug for buildtype keeps optimization level to be 0 and debug mode enabled - https://mesonbuild.com/Builtin-options.html, which IMO isn't desirable for release.
If you want more fine-grained control, buildtype can be plain and specify optimization -o2 with meson variables.

I missed that it was on the default option section. Sounds reasonable

2021-03-02 05:01 UTC, merged