[Util] Delete internal namespace
nnstreamer/nntrainer pull request #956
Opened 2021-02-17 04:50 UTC by zhoonit

This patch removes internal namespace from nntrainer::exception

**Self evaluation:**
1. Build test: [X]Passed [ ]Failed [ ]Skipped
2. Run test: [X]Passed [ ]Failed [ ]Skipped

Signed-off-by: Jihoon Lee <jhoon.it.lee@samsung.com>

2021-02-17 09:23 UTC, lhs8928 approved these changes
LGTM

2021-02-22 04:47 UTC, kparichay requested changes
The description talks about removing `internal` namespace.
However, the namespace still exists at line 45 of nntrainer/nntrainer_error.h

2021-02-22 06:43 UTC, zhoonit commented
> The description talks about removing `internal` namespace.
> However, the namespace still exists at line 45 of nntrainer/nntrainer_error.h

I think it was gone during rebase, thanks for noticing it :)

2021-03-02 04:17 UTC, zhoonit commented
v2. Added a commit to fix potention gcc-9 parenthesis problem.

2021-03-02 05:10 UTC, kparichay approved these changes
LGTM

2021-03-02 06:08 UTC, jijoongmoon approved these changes
LGTM

2021-03-02 06:08 UTC, merged